name: Tool
version: 6.0.0
versionCode: '600'
folder: ''
path: 'D:/Ksr/code/node/package-npm/src'
server: 'http://localhost:18080/api/'
time_difference: 6
theme: '0'
id: '1'
email: 475521357@qq.com
password: '0'
appKey: 5935A2EE667043FEA37971DC8A42C626
appSecret: 83FEC2290146405DB7C0D9E258E7865F
